
#pragma once

#ifdef AURIX

#define IFX_INTPRIO_TIM0_CH0 100
#define IFX_INTPRIO_TIM0_CH1 101
#define IFX_INTPRIO_TIM0_CH2 102
#define IFX_INTPRIO_TIM0_CH3 103
#define IFX_INTPRIO_TIM0_CH4 104
#define IFX_INTPRIO_TIM0_CH5 105
#define IFX_INTPRIO_TIM0_CH6 106
#define IFX_INTPRIO_TIM0_CH7 107
#define IFX_INTPRIO_TIM1_CH0 110
#define IFX_INTPRIO_TIM1_CH1 111
#define IFX_INTPRIO_TIM1_CH2 112
#define IFX_INTPRIO_TIM1_CH3 113
#define IFX_INTPRIO_TIM1_CH4 114
#define IFX_INTPRIO_TIM1_CH5 115
#define IFX_INTPRIO_TIM1_CH6 116
#define IFX_INTPRIO_TIM1_CH7 117
#define IFX_INTPRIO_TIM2_CH0 120
#define IFX_INTPRIO_TIM2_CH1 121
#define IFX_INTPRIO_TIM2_CH2 122
#define IFX_INTPRIO_TIM2_CH3 123
#define IFX_INTPRIO_TIM2_CH4 124
#define IFX_INTPRIO_TIM2_CH5 125
#define IFX_INTPRIO_TIM2_CH6 126
#define IFX_INTPRIO_TIM2_CH7 127
#define IFX_INTPRIO_TIM3_CH0 130
#define IFX_INTPRIO_TIM3_CH1 131
#define IFX_INTPRIO_TIM3_CH2 132
#define IFX_INTPRIO_TIM3_CH3 133
#define IFX_INTPRIO_TIM3_CH4 134
#define IFX_INTPRIO_TIM3_CH5 135
#define IFX_INTPRIO_TIM3_CH6 136
#define IFX_INTPRIO_TIM3_CH7 137

#define IFX_INTPRIO_TOM0_CH0_1 60
#define IFX_INTPRIO_TOM0_CH2_3 61
#define IFX_INTPRIO_TOM0_CH4_5 62
#define IFX_INTPRIO_TOM0_CH6_7 63
#define IFX_INTPRIO_TOM0_CH8_9 64
#define IFX_INTPRIO_TOM0_CH10_11 65
#define IFX_INTPRIO_TOM0_CH12_13 66
#define IFX_INTPRIO_TOM0_CH14_15 67

#define IFX_INTPRIO_TOM1_CH0_1 70
#define IFX_INTPRIO_TOM1_CH2_3 71
#define IFX_INTPRIO_TOM1_CH4_5 72
#define IFX_INTPRIO_TOM1_CH6_7 73
#define IFX_INTPRIO_TOM1_CH8_9 74
#define IFX_INTPRIO_TOM1_CH10_11 75
#define IFX_INTPRIO_TOM1_CH12_13 76
#define IFX_INTPRIO_TOM1_CH14_15 77

#define IFX_INTPRIO_ASCLIN_USART1_TX 10
#define IFX_INTPRIO_ASCLIN_USART1_RX 11
#define IFX_INTPRIO_ASCLIN_USART2_TX 12
#define IFX_INTPRIO_ASCLIN_USART2_RX 13
#define IFX_INTPRIO_ASCLIN_USART3_TX 14
#define IFX_INTPRIO_ASCLIN_USART3_RX 15
#define IFX_INTPRIO_ASCLIN_USART4_TX 16
#define IFX_INTPRIO_ASCLIN_USART4_RX 17

#define IFX_INTPRIO_QSPI_SPI1_TX  20
#define IFX_INTPRIO_QSPI_SPI1_RX  21
#define IFX_INTPRIO_QSPI_SPI2_TX  22
#define IFX_INTPRIO_QSPI_SPI2_RX  23
#define IFX_INTPRIO_QSPI_SPI3_TX  24
#define IFX_INTPRIO_QSPI_SPI3_RX  25

#else

// can't use 0
#define NVIC_PRIO_MAX                      NVIC_BUILD_PRIORITY(0, 1)
#define NVIC_PRIO_TIMER                    NVIC_BUILD_PRIORITY(1, 1)
#define NVIC_PRIO_BARO_EXTI                NVIC_BUILD_PRIORITY(0x0f, 0x0f)
#define NVIC_PRIO_SONAR_EXTI               NVIC_BUILD_PRIORITY(2, 0)  // maybe increate slightly
#define NVIC_PRIO_TRANSPONDER_DMA          NVIC_BUILD_PRIORITY(3, 0)
#define NVIC_PRIO_GYRO_INT_EXTI             NVIC_BUILD_PRIORITY(0x0f, 0x0f)
#define NVIC_PRIO_MAG_INT_EXTI             NVIC_BUILD_PRIORITY(0x0f, 0x0f)
#define NVIC_PRIO_WS2811_DMA               NVIC_BUILD_PRIORITY(1, 2)  // TODO - is there some reason to use high priority? (or to use DMA IRQ at all?)
#define NVIC_PRIO_SERIALUART1_TXDMA        NVIC_BUILD_PRIORITY(1, 1)
#define NVIC_PRIO_SERIALUART1_RXDMA        NVIC_BUILD_PRIORITY(1, 1)
#define NVIC_PRIO_SERIALUART1              NVIC_BUILD_PRIORITY(1, 1)
#define NVIC_PRIO_SERIALUART2_TXDMA        NVIC_BUILD_PRIORITY(1, 0)
#define NVIC_PRIO_SERIALUART2_RXDMA        NVIC_BUILD_PRIORITY(1, 1)
#define NVIC_PRIO_SERIALUART2              NVIC_BUILD_PRIORITY(1, 2)
#define NVIC_PRIO_SERIALUART3_TXDMA        NVIC_BUILD_PRIORITY(1, 0)
#define NVIC_PRIO_SERIALUART3_RXDMA        NVIC_BUILD_PRIORITY(1, 1)
#define NVIC_PRIO_SERIALUART3              NVIC_BUILD_PRIORITY(1, 2)
#define NVIC_PRIO_SERIALUART4_TXDMA        NVIC_BUILD_PRIORITY(1, 0)
#define NVIC_PRIO_SERIALUART4_RXDMA        NVIC_BUILD_PRIORITY(1, 1)
#define NVIC_PRIO_SERIALUART4              NVIC_BUILD_PRIORITY(1, 2)
#define NVIC_PRIO_SERIALUART5_TXDMA        NVIC_BUILD_PRIORITY(1, 0)
#define NVIC_PRIO_SERIALUART5_RXDMA        NVIC_BUILD_PRIORITY(1, 1)
#define NVIC_PRIO_SERIALUART5              NVIC_BUILD_PRIORITY(1, 2)
#define NVIC_PRIO_SERIALUART6_TXDMA        NVIC_BUILD_PRIORITY(1, 0)
#define NVIC_PRIO_SERIALUART6_RXDMA        NVIC_BUILD_PRIORITY(1, 1)
#define NVIC_PRIO_SERIALUART6              NVIC_BUILD_PRIORITY(1, 2)
#define NVIC_PRIO_SERIALUART7_TXDMA        NVIC_BUILD_PRIORITY(1, 0)
#define NVIC_PRIO_SERIALUART7_RXDMA        NVIC_BUILD_PRIORITY(1, 1)
#define NVIC_PRIO_SERIALUART7              NVIC_BUILD_PRIORITY(1, 2)
#define NVIC_PRIO_SERIALUART8_TXDMA        NVIC_BUILD_PRIORITY(1, 0)
#define NVIC_PRIO_SERIALUART8_RXDMA        NVIC_BUILD_PRIORITY(1, 1)
#define NVIC_PRIO_SERIALUART8              NVIC_BUILD_PRIORITY(1, 2)
#define NVIC_PRIO_I2C_ER                   NVIC_BUILD_PRIORITY(0, 0)
#define NVIC_PRIO_I2C_EV                   NVIC_BUILD_PRIORITY(0, 0)
#define NVIC_PRIO_USB                      NVIC_BUILD_PRIORITY(2, 0)
#define NVIC_PRIO_USB_WUP                  NVIC_BUILD_PRIORITY(1, 0)
#define NVIC_PRIO_SONAR_ECHO               NVIC_BUILD_PRIORITY(0x0f, 0x0f)
#define NVIC_PRIO_MPU_DATA_READY           NVIC_BUILD_PRIORITY(0x0f, 0x0f)
#define NVIC_PRIO_MAG_DATA_READY           NVIC_BUILD_PRIORITY(0x0f, 0x0f)
#define NVIC_PRIO_CALLBACK                 NVIC_BUILD_PRIORITY(0x0f, 0x0f)
#define NVIC_PRIO_MAX7456_DMA              NVIC_BUILD_PRIORITY(3, 0)

#ifdef USE_HAL_DRIVER
// utility macros to join/split priority
#define NVIC_PRIORITY_GROUPING NVIC_PRIORITYGROUP_2
#define NVIC_BUILD_PRIORITY(base,sub) (((((base)<<(4-(7-(NVIC_PRIORITY_GROUPING))))|((sub)&(0x0f>>(7-(NVIC_PRIORITY_GROUPING)))))<<4)&0xf0)
#define NVIC_PRIORITY_BASE(prio) (((prio)>>(4-(7-(NVIC_PRIORITY_GROUPING))))>>4)
#define NVIC_PRIORITY_SUB(prio) (((prio)&(0x0f>>(7-(NVIC_PRIORITY_GROUPING))))>>4)
#else
// utility macros to join/split priority
#define NVIC_PRIORITY_GROUPING NVIC_PriorityGroup_2
#define NVIC_BUILD_PRIORITY(base,sub) (((((base)<<(4-(7-(NVIC_PRIORITY_GROUPING>>8))))|((sub)&(0x0f>>(7-(NVIC_PRIORITY_GROUPING>>8)))))<<4)&0xf0)
#define NVIC_PRIORITY_BASE(prio) (((prio)>>(4-(7-(NVIC_PRIORITY_GROUPING>>8))))>>4)
#define NVIC_PRIORITY_SUB(prio) (((prio)&(0x0f>>(7-(NVIC_PRIORITY_GROUPING>>8))))>>4)
#endif

#endif
